name: CD for RiotWatcher

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: publish to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python 3.13
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.pypi_password }}
  
